name: Validate Themes

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: pull_request

jobs:
  validate-themes:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        
      - name: Override registry
        run: yarn config set registry "https://registry.npmjs.org"

      - uses: mskelton/setup-yarn@v3

      - name: Install dependencies
        run: yarn

      - name: Validate themes
        run: |
          yarn validate-themes
